"""
Stores alerts generated by the AI pipeline. Each alert references a device
and carries a type, severity, and human-readable message. Operators acknowledge
alerts via the dashboard; the acknowledged field tracks that state as 0/1.
"""

from sqlalchemy import Column, Float, Integer, Text
from database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    device_id    = Column(Text, nullable=False)
    timestamp    = Column(Text)                   # ISO 8601 as TEXT; set at insert time
    alert_type   = Column(Text)                   # sos_signal | cardiac_anomaly | no_movement
                                                  # | connectivity_loss | ml_anomaly
                                                  # | p1_classification | uav_battery_low
    severity     = Column(Text)                   # critical | warning | info
    message      = Column(Text)
    acknowledged = Column(Integer, default=0)     # 0/1 — toggled by operator via PATCH
    ai_confidence = Column(Float, default=1.0)    # 0.0–1.0; rule-based alerts use 1.0
